import os

TABOR_SEGMENT_MIN_LENGTH = int(os.environ.get("TABOR_SEGMENT_MIN_LENGTH", 1024))
TABOR_SEGMENT_MIN_SIZE_STEP = int(os.environ.get("TABOR_SEGMENT_MIN_SIZE_STEP", 32))
TABOR_SEGMENT_VOLT_MIN = float(os.environ.get("TABOR_SEGMENT_VOLT_MIN", -10))
TABOR_SEGMENT_VOLT_MAX = float(os.environ.get("TABOR_SEGMENT_VOLT_MAX", 10))
